name: Build TFS for Windows

on:
  push:
    paths:
      - 'src/**'
      - 'vc17/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    name: Build TFS
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          vcpkg install boost-iostreams:x64-windows
          vcpkg install boost-filesystem:x64-windows
          vcpkg install boost-asio:x64-windows
          vcpkg install boost-system:x64-windows
          vcpkg install boost-variant:x64-windows
          vcpkg install boost-lockfree:x64-windows
          vcpkg install cryptopp:x64-windows
          vcpkg install luajit:x64-windows
          vcpkg install libmariadb:x64-windows
          vcpkg install pugixml:x64-windows
          vcpkg install mpir:x64-windows
          vcpkg install spdlog:x64-windows
          vcpkg integrate install

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Build solution (Release x64)
        run: |
          $env:VCPKG_ROOT="C:\vcpkg"
          msbuild vc17/themodernserver.sln /p:Configuration=Release /p:Platform=x64 /p:VcpkgTriplet=x64-windows

      - name: Archive .exe and .dll
        run: |
          Compress-Archive -Path vc17\*.exe, vc17\*.dll -DestinationPath OT.zip

      - name: Upload build
        uses: actions/upload-artifact@v4
        with:
          name: OT Build
          path: |
            vc17/*.exe
            vc17/*.dll
            OT.zip
