name: Build TFS 1.4.2 (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Install vcpkg dependencies
      run: |
        vcpkg install boost-iostreams:x64-windows
        vcpkg install boost-filesystem:x64-windows
        vcpkg install boost-asio:x64-windows
        vcpkg install boost-system:x64-windows
        vcpkg install boost-variant:x64-windows
        vcpkg install boost-lockfree:x64-windows
        vcpkg install cryptopp:x64-windows
        vcpkg install luajit:x64-windows
        vcpkg install libmariadb:x64-windows
        vcpkg install pugixml:x64-windows
        vcpkg install mpir:x64-windows
        vcpkg install spdlog:x64-windows

    - name: Build TFS in Release
      run: |
        msbuild OT.sln /p:Configuration=Release /p:Platform=x64

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: tfs-binaries
        path: |
          **\Release\*.exe
          **\Release\*.dll
