name: Build TFS 1.4.2 on Windows

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone vcpkg
        run: git clone https://github.com/microsoft/vcpkg.git

      - name: Bootstrap vcpkg
        run: .\vcpkg\bootstrap-vcpkg.bat

      - name: Install dependencies with vcpkg
        run: |
          .\vcpkg\vcpkg.exe install boost-iostreams:x64-windows boost-asio:x64-windows boost-system:x64-windows boost-variant:x64-windows boost-lockfree:x64-windows boost-locale:x64-windows boost-beast:x64-windows boost-json:x64-windows luajit:x64-windows libmariadb:x64-windows pugixml:x64-windows openssl:x64-windows fmt:x64-windows zlib:x64-windows

      - name: Patch io_service to io_context
        shell: powershell
        run: |
          Get-ChildItem -Path src -Recurse -Include *.cpp,*.h | ForEach-Object {
            (Get-Content $_.FullName) -replace 'boost::asio::io_service', 'boost::asio::io_context' |
            Set-Content $_.FullName
          }

      - name: Build solution in Release mode
        run: msbuild vc17/themodernserver.sln /p:Configuration=Release /p:Platform=x64

      - name: Upload compiled files
        uses: actions/upload-artifact@v4
        with:
          name: server-build
          path: |
            vc17/**/*.exe
            vc17/**/*.dll
