version: 1.0.{build}
image: Visual Studio 2019

clone_depth: 1

install:
  - cmd: >-
      git submodule update --init --recursive &&
      choco install premake5 --yes

before_build:
  - cmd: premake5 vs2019

build:
  project: builds\vc16\theforgottenserver.sln
  parallel: true
  verbosity: minimal

artifacts:
  - path: builds\vc16\Release\theforgottenserver.exe
    name: TFS_1.4.2

notifications:
  - provider: Email
    to:
      - seuemail@example.com
    on_build_success: true
    on_build_failure: true
