name: Build TFS for Windows

on:
  push:
    paths:
      - 'src/**'
      - 'vc17/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  build:
    name: Compile on Windows
    runs-on: windows-latest

    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies with vcpkg
        run: |
          vcpkg install boost-iostreams:x64-windows
          vcpkg install boost-filesystem:x64-windows
          vcpkg install boost-asio:x64-windows
          vcpkg install boost-system:x64-windows
          vcpkg install boost-variant:x64-windows
          vcpkg install boost-lockfree:x64-windows
          vcpkg install cryptopp:x64-windows
          vcpkg install luajit:x64-windows
          vcpkg install libmariadb:x64-windows
          vcpkg install pugixml:x64-windows
          vcpkg install mpir:x64-windows
          vcpkg install spdlog:x64-windows

      - name: Set up MSBuild path
        uses: microsoft/setup-msbuild@v2

      - name: Build the solution
        run: |
          msbuild vc17/themodernserver.sln /p:Configuration=Release /p:Platform=x64

      - name: Archive executable
        run: |
          Compress-Archive -Path vc17\*.exe -DestinationPath OT.zip

      - name: Upload .exe as artifact
        uses: actions/upload-artifact@v4
        with:
          name: OT Build
          path: |
            vc17/*.exe
            vc17/*.dll
            OT.zip
