name: Build TFS 1.4.2 on Windows

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install vcpkg dependencies
        run: |
          ./vcpkg install --triplet x64-windows boost-iostreams boost-asio boost-system boost-variant boost-lockfree boost-locale boost-beast boost-json luajit libmariadb pugixml openssl fmt zlib

      - name: Patch source (fix io_service)
        shell: powershell
        run: |
          Get-ChildItem -Path src -Recurse -Include *.cpp,*.h | ForEach-Object {
            (Get-Content $_.FullName) -replace 'boost::asio::io_service', 'boost::asio::io_context' |
            Set-Content $_.FullName
          }

      - name: Build solution in Release mode
        run: msbuild vc17/themodernserver.sln /p:Configuration=Release /p:Platform=x64

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: tfs-binaries
          path: |
            vc17/**/*.exe
            vc17/**/*.dll
