name: Build TFS 1.4.2 on Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build on Windows
    runs-on: windows-2019

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install premake5
        run: choco install premake5 --yes

      - name: Generate Visual Studio project files
        run: premake5 vs2019

      - name: Build solution
        run: msbuild builds/vc16/theforgottenserver.sln /p:Configuration=Release /m

      - name: Upload theforgottenserver.exe
        uses: actions/upload-artifact@v4
        with:
          name: theforgottenserver
          path: builds/vc16/Release/theforgottenserver.exe
